# Site settings
title: Alex Pate
email: proto.merkabah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Where I can wax poetically about programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xeinherjar.github.io" # the base hostname & protocol for your site
twitter_username: einherjar
github_username:  xeinherjar

# Build settings
markdown: kramdown
